Pipeline {
  agent any

  environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

  stages {
    stage ("initial cleanup") {
      steps {
        dir ("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage ('checkout SCM') {
      steps {
        git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Uzuazoraro/ansible-config-mgt.git'
      }
    }

    stage ('Prepare Ansible For Execution') {
      steps {
        sh 'echo ${WORKSPACE}'
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
      }
    }

    stage('Run Ansible Playbook') {
      steps {
        ansiblePlaybook become: true, colorized: true, credentialsId: '1c951ee5-72d1-40ec-a249-d40bf0d43875', disableHostKeyChecking: true, installation: 'Ansible2', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
      }
    }

    stage('Clean Workspace after build') {
      steps {
        cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuild: true, cleanWhenUnstable: true, deleteDirs: true)
      }
    }
  }

}